### PR TITLE
fixed performance monitor dep check

### PR DESCRIPTION
**Pull request by fsjovatsen**

### CODE REVIEW

**Review by asgeirn — CHANGES_REQUESTED** [review]
This should not be required, as the `@EnableFintCache` configuration annotation already has this condition on the configuration class.

**Comment by asgeirn** [comment]
I suggest we remove the performance monitoring feature for now - the configuration creates conflicts with using `FintCache` without the `@EnableFintCache` annotation.

**Comment by jarlehansen** [comment]
What exactly was the problem with the performance monitor?

**Comment by asgeirn** [comment]
If you include `fint-cache` as a dependency in a project, but not using `@EnableFintCache` or `CacheManager`, you get this error:

    ***************************
    APPLICATION FAILED TO START
    ***************************
    
    Description:
    
    Parameter 0 of constructor in no.fint.cache.monitoring.PerformanceMonitorController required a bean of type 'no.fint.cache.monitoring.PerformanceMonitor' that could not be found.
    
    The following candidates were found but could not be injected:
    	- Bean method 'performanceMonitor' in 'PerformanceConfig' not loaded because @ConditionalOnProperty (fint.cache.performance-monitor=true) did not find property 'fint.cache.performance-monitor'
    
    
    Action:
    
    Consider revisiting the entries above or defining a bean of type 'no.fint.cache.monitoring.PerformanceMonitor' in your configuration.
    
    
    Process finished with exit code 1

**Comment by asgeirn** [comment]
This is probably because this class has `@RestController` and `@RequestMapping` annotations.

**Review by asgeirn — APPROVED** [review]

**Pull request merged**
