### PR TITLE
HazelcastCache delegates to FintCache

### PR DESCRIPTION
**Pull request by asgeirn**
This PR should solve the race condition where clients fetching the cache while it's updated is seeing an empty or incomplete cache, as described in #9 

Furthermore, all stream operations are made parallel to increase performance.

### CODE REVIEW

**Comment by jarlehansen** [comment]
@asgeirn do we have performance measurements of this? if not, I would like to add a simple solution we can easily enable/disable that logs the execution times of methods in CacheService. Just so we can get a better idea where exactly the time is being spent.

**Comment by asgeirn** [comment]
> @asgeirn do we have performance measurements of this? if not, I would like to add a simple solution we can easily enable/disable that logs the execution times of methods in CacheService. Just so we can get a better idea where exactly the time is being spent.

Good idea!  We don't have any benchmarks, that should definitely be in place to assess the impact of modifications.

**Review by jarlehansen — APPROVED** [review]
Lets see if the improves the performance

**Comment by asgeirn** [comment]
@jarlehansen, could you have a second look?  I've rebased it onto the latest changes in master.

**Review by jarlehansen — APPROVED** [review]

**Pull request merged**
